# Generated by Django 4.2.16 on 2024-11-23 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Unique name for the fee structure (e.g., 'Term 1 Fees').", max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total fee amount for the grade.', max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount that has been paid towards the total fee.', max_digits=10)),
                ('description', models.TextField(null=True)),
                ('fee_type', models.CharField(choices=[('ADMISSION', 'Admission Fee'), ('TERM', 'Term Fee'), ('ONCE', 'One-time Fee'), ('DAILY', 'Daily Fee')], default='TERM', help_text='Type of fee structure.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='school_fee.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school_fee.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school_fee.school')),
            ],
            options={
                'unique_together': {('name', 'date_of_birth')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('reference_number', models.CharField(max_length=100, null=True, unique=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='school_fee.fee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='school_fee.student')),
            ],
            options={
                'ordering': ['-date_paid'],
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='school_fee.school'),
        ),
        migrations.AddField(
            model_name='fee',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Grade this fee structure applies to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='school_fee.grade'),
        ),
        migrations.AddField(
            model_name='fee',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Students associated with this fee.', related_name='fees', to='school_fee.student'),
        ),
        migrations.AddField(
            model_name='fee',
            name='term',
            field=models.ForeignKey(help_text='Term this fee structure applies to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='school_fee.term'),
        ),
    ]
